---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
library("nlme")
library("mgcv")
library("lattice")
library("tidyverse")
library("stringr") 
library("plot3D")
```

#### IMPUTE USING KNN
```{r}
setwd('C:/Users/danie/OneDrive/Documents/stats501/STATS501_project/data')
knn_dat = read_delim('violenceKNN.csv', delim = ",")
```
```{r}
#econ_dat$`Median Household Income in Dollars` = substring(econ_dat$`Median Household Income in Dollars`,2) 
#econ_dat$`Median Household Income in Dollars` = str_replace_all(econ_dat$`Median Household Income in Dollars`, "[,]", "") 
#as.double(econ_dat$`Median Household Income in Dollars`)

#setwd('C:/Users/danie/OneDrive/Documents/stats501/STATS501_project/data')
#write.csv(econ_dat, 'violenceKNN.csv')
```

```{r}
## Group by County

# Use all age poverty percent
mod_all_reml_knn = lme(violenceScore ~ AllAgesInPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = knn_dat)

mod_all_ml_knn = lme(violenceScore ~ AllAgesInPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, method = "ML", data = knn_dat)

# Use under 18 poverty percent
mod_und_reml_knn = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = knn_dat)

mod_und_ml_knn = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, method = "ML", data = knn_dat)
```

```{r}
summary(mod_all_reml_knn)
summary(mod_all_ml_knn)
summary(mod_und_reml_knn)
summary(mod_und_ml_knn)
```

```{r}
# Dropping each predictor

mod_und_reml_pov_knn = lme(violenceScore ~ MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = knn_dat)

mod_und_reml_med_knn = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = knn_dat)


mod_und_reml_unemp_knn = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + Population + SNAP + year, random = ~ 1 | sitename, data = knn_dat)

mod_und_reml_pop_knn = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + SNAP + year, random = ~ 1 | sitename, data = knn_dat)

mod_und_reml_snap_knn = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + year, random = ~ 1 | sitename, data = knn_dat)

mod_und_reml_year_knn = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP, random = ~ 1 | sitename, data = knn_dat)
```

```{r}
# Using under 18 poverty rate
mod_und_reml_2b_knn = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + SNAP + year, random = ~ 1 | sitename, data = knn_dat)
mod_und_reml_3_knn = lme(violenceScore ~ UnemploymentRate + SNAP + year, random = ~ 1 | sitename, data = knn_dat)

# F test comparing with/without poverty percent
anova(mod_und_reml_2b_knn, mod_und_reml_3_knn, test = "F")
```

```{r}
# Using all age poverty percent
mod_und_ml_2b_knn = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + SNAP + year, random = ~ 1 | sitename, data = knn_dat, method = "ML")
mod_und_ml_3_knn = lme(violenceScore ~ UnemploymentRate + SNAP + year, random = ~ 1 | sitename, data = knn_dat, method = "ML")

# F test comparing with/without poverty percent
anova(mod_und_ml_2b_knn, mod_und_ml_3_knn, test = "F")
```

```{r}
# Find how to compare between reml and ml
```



```{r}
scatter3D(knn_dat$UnemploymentRate, knn_dat$SNAP, knn_dat$violenceScore, col.var = as.integer(knn_dat$sitename), col = c(1:15), phi = 0)
```


###### IMPUTE USING MEAN
```{r}
setwd('C:/Users/danie/OneDrive/Documents/stats501/STATS501_project/data')
mean_dat = read_delim('violenceMean.csv', delim = ",") %>% transmute(year = year, sitename = sitename, violenceScore = `violence score`, AllAgesInPovertyPercent = `All Ages in Poverty Percent`, UnderAge18InPovertyPercent = `Under Age 18 in Poverty Percent`, MedianHouseholdIncomeInDollars = `Median Household Income in Dollars`, UnemploymentRate = `Unemployment Rate`, Population = Population, SNAP = `SNAP($/Person)`)
```
```{r}
## Group by County

# Use all age poverty percent
mod_all_reml_mean = lme(violenceScore ~ AllAgesInPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = mean_dat)

mod_all_ml_mean = lme(violenceScore ~ AllAgesInPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, method = "ML", data = mean_dat)

# Use under 18 poverty percent
mod_und_reml_mean = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = mean_dat)

mod_und_ml_mean = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, method = "ML", data = mean_dat)
```

```{r}
summary(mod_all_reml_mean)
summary(mod_all_ml_mean)
summary(mod_und_reml_mean)
summary(mod_und_ml_mean)
```

```{r}
# Dropping each predictor

mod_und_reml_pov_mean = lme(violenceScore ~ MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = mean_dat)

mod_und_reml_med_mean = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = mean_dat)


mod_und_reml_unemp_mean = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + Population + SNAP + year, random = ~ 1 | sitename, data = mean_dat)

mod_und_reml_pop_mean = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + SNAP + year, random = ~ 1 | sitename, data = mean_dat)

mod_und_reml_snap_mean = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + year, random = ~ 1 | sitename, data = mean_dat)

mod_und_reml_year_mean = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP, random = ~ 1 | sitename, data = mean_dat)
```

```{r}
# Using under 18 poverty rate
mod_und_reml_2_mean = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = mean_dat)
mod_und_reml_2b_mean = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + SNAP + year, random = ~ 1 | sitename, data = mean_dat)
mod_und_reml_3_mean = lme(violenceScore ~ UnemploymentRate + SNAP + year, random = ~ 1 | sitename, data = mean_dat)

# F test comparing with/without poverty percent
anova(mod_und_reml_2_mean, mod_und_reml_2b_mean, mod_und_reml_3_mean, test = "F")
```

```{r}
# Using all age poverty percent
mod_und_ml_2_mean = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = mean_dat, method = "ML")
mod_und_ml_2b_mean = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + SNAP + year, random = ~ 1 | sitename, data = mean_dat, method = "ML")
mod_und_ml_3_mean = lme(violenceScore ~ UnemploymentRate + SNAP + year, random = ~ 1 | sitename, data = mean_dat, method = "ML")

# F test comparing with/without poverty percent
anova(mod_und_ml_2_mean, mod_und_ml_2b_mean, mod_und_ml_3_mean, test = "F")
```

###### IMPUTE USING MEDIAN
```{r}
setwd('C:/Users/danie/OneDrive/Documents/stats501/STATS501_project/data')
med_dat = read_delim('violenceMedian.csv', delim = ",")
```
```{r}
## Group by County

# Use all age poverty percent
mod_all_reml_med = lme(violenceScore ~ AllAgesInPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = med_dat)

mod_all_ml_med = lme(violenceScore ~ AllAgesInPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, method = "ML", data = med_dat)

# Use under 18 poverty percent
mod_und_reml_med = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = med_dat)

mod_und_ml_med = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, method = "ML", data = med_dat)
```

```{r}
summary(mod_all_reml_med)
summary(mod_all_ml_med)
summary(mod_und_reml_med)
summary(mod_und_ml_med)
```

```{r}
# Dropping each predictor

mod_und_reml_pov_med = lme(violenceScore ~ MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = med_dat)

mod_und_reml_med_med = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = med_dat)


mod_und_reml_unemp_med = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + Population + SNAP + year, random = ~ 1 | sitename, data = med_dat)

mod_und_reml_pop_med = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + SNAP + year, random = ~ 1 | sitename, data = med_dat)

mod_und_reml_snap_med = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + year, random = ~ 1 | sitename, data = med_dat)

mod_und_reml_year_med = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP, random = ~ 1 | sitename, data = med_dat)
```

```{r}
# Using under 18 poverty rate
mod_und_reml_2_med = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + Population + SNAP  + year, random = ~ 1 | sitename, data = med_dat)
mod_und_reml_2b_med = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + SNAP  + year, random = ~ 1 | sitename, data = med_dat)
mod_und_reml_3_med = lme(violenceScore ~ UnemploymentRate + SNAP  + year, random = ~ 1 | sitename, data = med_dat)

# F test comparing with/without poverty percent
anova(mod_und_reml_2_med, mod_und_reml_2b_med, mod_und_reml_3_med, test = "F")
```

```{r}
# Using all age poverty percent
mod_und_ml_2_med = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + Population + SNAP  + year, random = ~ 1 | sitename, data = med_dat, method = "ML")
mod_und_ml_2b_med = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + SNAP  + year, random = ~ 1 | sitename, data = med_dat, method = "ML")
mod_und_ml_3_med = lme(violenceScore ~ UnemploymentRate + SNAP  + year, random = ~ 1 | sitename, data = med_dat, method = "ML")

# F test comparing with/without poverty percent
anova(mod_und_ml_2_med, mod_und_ml_2b_med, mod_und_ml_3_med, test = "F")
```


###### IMPUTE USING MODE
```{r}
setwd('C:/Users/danie/OneDrive/Documents/stats501/STATS501_project/data')
mode_dat = read_delim('violenceMedian.csv', delim = ",")
```
```{r}
## Group by County

# Use all age poverty percent
mod_all_reml_mode = lme(violenceScore ~ AllAgesInPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = mode_dat)

mod_all_ml_mode = lme(violenceScore ~ AllAgesInPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, method = "ML", data = mode_dat)

# Use under 18 poverty percent
mod_und_reml_mode = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = mode_dat)

mod_und_ml_mode = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, method = "ML", data = mode_dat)
```

```{r}
summary(mod_all_reml_mode)
summary(mod_all_ml_mode)
summary(mod_und_reml_mode)
summary(mod_und_ml_mode)
```

```{r}
# Dropping each predictor

mod_und_reml_pov_mode = lme(violenceScore ~ MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = mode_dat)

mod_und_reml_med_mode = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = mode_dat)


mod_und_reml_unemp_mode = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + Population + SNAP + year, random = ~ 1 | sitename, data = mode_dat)

mod_und_reml_pop_mode = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + SNAP + year, random = ~ 1 | sitename, data = mode_dat)

mod_und_reml_snap_mode = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + year, random = ~ 1 | sitename, data = mode_dat)

mod_und_reml_year_mode = lme(violenceScore ~ UnderAge18InPovertyPercent + MedianHouseholdIncomeInDollars + UnemploymentRate + Population + SNAP, random = ~ 1 | sitename, data = mode_dat)
```

```{r}
# Using under 18 poverty rate
mod_und_reml_2_mode = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = mode_dat)
mod_und_reml_2b_mode = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + SNAP + year, random = ~ 1 | sitename, data = mode_dat)
mod_und_reml_3_mode = lme(violenceScore ~ UnemploymentRate + SNAP + year, random = ~ 1 | sitename, data = mode_dat)

# F test comparing with/without poverty percent
anova(mod_und_reml_2_mode, mod_und_reml_2b_mode, mod_und_reml_3_mode, test = "F")
```

```{r}
# Using all age poverty percent
mod_und_ml_2_mode = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + Population + SNAP + year, random = ~ 1 | sitename, data = mode_dat, method = "ML")
mod_und_ml_2b_mode = lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + SNAP + year, random = ~ 1 | sitename, data = mode_dat, method = "ML")
mod_und_ml_3_mode = lme(violenceScore ~ UnemploymentRate + SNAP + year, random = ~ 1 | sitename, data = mode_dat, method = "ML")

# F test comparing with/without poverty percent
anova(mod_und_ml_2_mode, mod_und_ml_2b_mode, mod_und_ml_3_mode, test = "F")
```

****** 
Warning in anova.lme(mod_und_reml_2_mode, mod_und_reml_2b_mode, mod_und_reml_3_mode,  :
  fitted objects with different fixed effects. REML comparisons are not meaningful.
  

Fit with year
Add quadratic turns
Interaction term
Make 3d plots see if you can get them to move

```{r}
summary(lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + SNAP + I(SNAP^2) + year, random = ~ 1 | sitename, data = mode_dat))
```
```{r}
summary(lme(violenceScore ~ UnderAge18InPovertyPercent*year + UnemploymentRate + SNAP + I(SNAP^2), random = ~ 1 | sitename, data = mode_dat))

summary(lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate*year + SNAP + I(SNAP^2), random = ~ 1 | sitename, data = mode_dat))

summary(lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + SNAP*year + I(SNAP^2), random = ~ 1 | sitename, data = mode_dat))

summary(lme(violenceScore ~ UnderAge18InPovertyPercent + UnemploymentRate + SNAP+ I(SNAP^2)*year, random = ~ 1 | sitename, data = mode_dat))

summary(lme(violenceScore ~ UnemploymentRate + SNAP+ I(SNAP^2)*year, random = ~ 1 | sitename, data = mode_dat))
```
```{r}
library(scatterplot3d)
library(rgl)
```
```{r}
with(mode_dat, plot3d(mode_dat$UnemploymentRate, mode_dat$SNAP, mode_dat$violenceScore, type= "s", col = as.integer(mode_dat$sitename)))
```


