---
title: "R Notebook"
output: html_notebook
---

```{r}
library("tidyverse")
library("dplyr")
library("mgcv")
library("mgcViz")
```

```{r}
setwd('C:/Users/danie/OneDrive/Documents/stats501/STATS501_project/data')
dat = read_delim('violenceKNNResp_wSex_NotSplitImp.csv', delim = ",")
knn_dat = read_delim('violenceKNN.csv', delim = ",") %>% select(-c(violenceScore))
split_dat = right_join(dat, knn_dat, by = c("year", "sitename")) %>% mutate(violenceScore = `violence score`)
```

```{r}
fit_spline = smooth.spline(split_dat$UnemploymentRate*split_dat$sex + split_dat$SNAP*split_dat$sex, split_dat$violenceScore)
plot(split_dat$SNAP, split_dat$violenceScore)
lines(fit_spline, col = "red")

plot(split_dat$UnemploymentRate, split_dat$violenceScore)
lines(fit_spline, col = "orange")
```


```{r}
fit_gam = gam(split_dat$violenceScore ~ s(split_dat$SNAP, by = split_dat$sex, bs = "cr", k = 12))

AIC(fit_gam)

fit_gam = getViz(fit_gam)

p = plot( sm(fit_gam, 1) ) 
p + l_fitLine(colour = "red") + 
    l_ciLine(mul = 5, colour = "blue", linetype = 2) + 
    l_points(shape = 19, size = 1, alpha = 0.1)
```


```{r}
fit_gam = gam(split_dat$violenceScore ~ s(split_dat$SNAP, bs = "cr", k = 12) + s(as.factor(split_dat$sitename), bs = "re"))

AIC(fit_gam)

fit_gam = getViz(fit_gam)

p = plot( sm(fit_gam, 1) ) 
p + l_fitLine(colour = "red") + 
    l_ciLine(mul = 5, colour = "blue", linetype = 2) + 
    l_points(shape = 19, size = 1, alpha = 0.1)
```

```{r}
fit_gam = gam(split_dat$violenceScore ~ s(split_dat$SNAP, by = split_dat$sex, bs = "cr", k = 12) + split_dat$UnemploymentRate + s(as.factor(split_dat$sitename), bs = "re"))

AIC(fit_gam)

fit_gam = getViz(fit_gam)

p = plot( sm(fit_gam, 1) ) 
p + l_fitLine(colour = "red") + 
    l_ciLine(mul = 5, colour = "blue", linetype = 2) + 
    l_points(shape = 19, size = 1, alpha = 0.1)
```

```{r}
fit_gam = gam(split_dat$violenceScore ~ s(split_dat$SNAP, by = split_dat$sex, bs = "cr", k = 20) + s(split_dat$UnemploymentRate, by = split_dat$sex, bs = "cr", k = 15) + s(as.factor(split_dat$sitename), bs = "re"))

AIC(fit_gam)

fit_gam = getViz(fit_gam)

p = plot( sm(fit_gam, 1) ) 
p + l_fitLine(colour = "red") + 
    l_ciLine(mul = 5, colour = "blue", linetype = 2) + 
    l_points(shape = 19, size = 1, alpha = 0.1)
```

```{r}
fit_gam = gam(split_dat$violenceScore ~ s(split_dat$UnemploymentRate, by = split_dat$sex, bs = "cr", k = 12) + s(split_dat$SNAP, by = split_dat$sex, bs = "cr", k = 12) + s(as.factor(split_dat$sitename), bs = "re"))

AIC(fit_gam)

fit_gam = getViz(fit_gam)

p = plot( sm(fit_gam, 1) ) 
p + l_fitLine(colour = "red") + 
    l_ciLine(mul = 5, colour = "blue", linetype = 2) + 
    l_points(shape = 19, size = 1, alpha = 0.1)
```


```{r}
fit_gam = gam(split_dat$violenceScore ~ s(split_dat$UnemploymentRate, by = split_dat$sex, bs = "cr", k = 12) + split_dat$SNAP + s(as.factor(split_dat$sitename), bs = "re"))

AIC(fit_gam)

fit_gam = getViz(fit_gam)

p = plot( sm(fit_gam, 1) ) 
p + l_fitLine(colour = "red") + 
    l_ciLine(mul = 5, colour = "blue", linetype = 2) + 
    l_points(shape = 19, size = 1, alpha = 0.1)
```




```{r}
fit_gam = gam(split_dat$violenceScore ~ split_dat$SNAP + s(split_dat$UnemploymentRate, by = split_dat$sex, bs = "cr", k = 12) +  s(as.factor(split_dat$sitename), bs = "re"))

AIC(fit_gam)

fit_gam = getViz(fit_gam)

p = plot( sm(fit_gam, 1) ) 
p + l_fitLine(colour = "red") + 
    l_ciLine(mul = 5, colour = "blue", linetype = 2) + 
    l_points(shape = 19, size = 1, alpha = 0.1)
```

```{r}
fit_gam = gam(split_dat$violenceScore ~ split_dat$SNAP + split_dat$UnemploymentRate +  s(as.factor(split_dat$sitename), bs = "re"))

AIC(fit_gam)

fit_gam = getViz(fit_gam)

p = plot( sm(fit_gam, 1) ) 
p + l_fitLine(colour = "red") + 
    l_ciLine(mul = 5, colour = "blue", linetype = 2) + 
    l_points(shape = 19, size = 1, alpha = 0.1)
```

```{r}
SNAP2 = split_dat$SNAP^2
SNAP3 = split_dat$SNAP^3

AIC(gam(violenceScore ~ sex*UnemploymentRate + sex*SNAP + SNAP2 + SNAP3 + s(as.factor(split_dat$sitename), bs = "re"), data = split_dat))
```

2 = sitename
3 = sex
```{r, warning=F}
library("gtools")

CrossValMSE = function(modelEqu, modelGroup, nLeftOut, dat, mseSplitOn) {
  
  leftOutCols = combinations(length(t(unique(split_dat[modelGroup]))), nLeftOut, v = t(unique(split_dat[modelGroup])))
  
  msesSplit = rep(0,dim(leftOutCols)[1])
  msesSplit_male = rep(0,dim(leftOutCols)[1])
  msesSplit_female = rep(0,dim(leftOutCols)[1])
  
  for (lo in 1:dim(leftOutCols)[1]) {
    dat_keep = split_dat %>% filter(sitename != leftOutCols[lo,1] & sitename != leftOutCols[lo,2])
    dat_keep$sitename = as.factor(dat_keep$sitename)
    
    dat_remove = split_dat %>% filter(sitename == leftOutCols[lo,1] | sitename == leftOutCols[lo,2])
    dat_remove$sitename = as.factor(dat_remove$sitename)
    

    gam_mod = gam(violenceScore ~ sex*UnemploymentRate + sex*SNAP + s(sitename, bs = "re"), data = dat_keep)

    pred = predict(gam_mod, dat_remove, exclude = "s(sitename)")
    
    msesSplit[lo] = sum((dat_remove$violenceScore - pred)^2) / length(pred)
    
    male_index = which(dat_remove$sex == 2)
    
    female_index = which(dat_remove$sex == 1)
    
    msesSplit_male[lo] = sum((dat_remove[male_index, "violenceScore"] - pred[male_index])^2) / length(pred[male_index])
    msesSplit_female[lo] = sum((dat_remove[female_index, "violenceScore"] - pred[female_index])^2) / length(pred[female_index])
          
    
    }#for
  
  
  return(list(mse = mean(msesSplit), mse_male = mean(msesSplit_male), mse_female = mean(msesSplit_female)))
  
}#function

CrossValMSE(modelEqu, 2, 2, split_dat, 3)
```

```{r, warning=F}
library("gtools")

CrossValMSE = function(k, modelGroup, nLeftOut, dat, mseSplitOn) {
  
  leftOutCols = combinations(length(t(unique(split_dat[modelGroup]))), nLeftOut, v = t(unique(split_dat[modelGroup])))
  
  msesSplit = rep(0,dim(leftOutCols)[1])
  msesSplit_male = rep(0,dim(leftOutCols)[1])
  msesSplit_female = rep(0,dim(leftOutCols)[1])
  
  for (lo in 1:dim(leftOutCols)[1]) {
    dat_keep = split_dat %>% filter(sitename != leftOutCols[lo,1] & sitename != leftOutCols[lo,2])
    dat_keep$sitename = as.factor(dat_keep$sitename)
    
    dat_remove = split_dat %>% filter(sitename == leftOutCols[lo,1] | sitename == leftOutCols[lo,2])
    dat_remove$sitename = as.factor(dat_remove$sitename)
    

    gam_mod = gam(violenceScore ~ s(SNAP, by = sex, bs = "cr", k = k) + s(UnemploymentRate, by = sex, bs = "cr", k = k) + s(sitename, bs = "re"), data = dat_keep)


    pred = predict(gam_mod, dat_remove, exclude = "s(sitename)")
    
    msesSplit[lo] = sum((dat_remove$violenceScore - pred)^2) / length(pred)
    
    male_index = which(dat_remove$sex == 2)
    
    female_index = which(dat_remove$sex == 1)
    
    msesSplit_male[lo] = sum((dat_remove[male_index, "violenceScore"] - pred[male_index])^2) / length(pred[male_index])
    msesSplit_female[lo] = sum((dat_remove[female_index, "violenceScore"] - pred[female_index])^2) / length(pred[female_index])
          
    
    }#for
  
  
  return(list(mse = mean(msesSplit), mse_male = mean(msesSplit_male), mse_female = mean(msesSplit_female)))
  
}#function

CrossValMSE(20, 2, 2, split_dat, 3)
CrossValMSE(15, 2, 2, split_dat, 3)
CrossValMSE(10, 2, 2, split_dat, 3)
CrossValMSE(5, 2, 2, split_dat, 3)
```


```{r, warning=F}
library("gtools")

CrossValMSE = function(modelEqu, modelGroup, nLeftOut, dat, mseSplitOn) {
  split_dat$SNAP2 = (split_dat$SNAP)^2
  split_dat$SNAP3 = (split_dat$SNAP)^3
  
  leftOutCols = combinations(length(t(unique(split_dat[modelGroup]))), nLeftOut, v = t(unique(split_dat[modelGroup])))
  
  msesSplit = rep(0,dim(leftOutCols)[1])
  msesSplit_male = rep(0,dim(leftOutCols)[1])
  msesSplit_female = rep(0,dim(leftOutCols)[1])
  
  for (lo in 1:dim(leftOutCols)[1]) {
    dat_keep = split_dat %>% filter(sitename != leftOutCols[lo,1] & sitename != leftOutCols[lo,2])
    dat_keep$sitename = as.factor(dat_keep$sitename)
    
    dat_remove = split_dat %>% filter(sitename == leftOutCols[lo,1] | sitename == leftOutCols[lo,2])
    dat_remove$sitename = as.factor(dat_remove$sitename)
    

    gam_mod = gam(violenceScore ~ sex*UnemploymentRate + sex*SNAP + SNAP2 + SNAP3 + s(sitename, bs = "re"), data = dat_keep)

    pred = predict(gam_mod, dat_remove, exclude = "s(sitename)")
    
    msesSplit[lo] = sum((dat_remove$violenceScore - pred)^2) / length(pred)
    
    male_index = which(dat_remove$sex == 2)
    
    female_index = which(dat_remove$sex == 1)
    
    msesSplit_male[lo] = sum((dat_remove[male_index, "violenceScore"] - pred[male_index])^2) / length(pred[male_index])
    msesSplit_female[lo] = sum((dat_remove[female_index, "violenceScore"] - pred[female_index])^2) / length(pred[female_index])
          
    
    }#for
  
  
  return(list(mse = mean(msesSplit), mse_male = mean(msesSplit_male), mse_female = mean(msesSplit_female)))
  
}#function

CrossValMSE(modelEqu, 2, 2, split_dat, 3)
```



